# Generated by Django 2.1 on 2018-10-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverinput', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='app_path',
        ),
        migrations.RemoveField(
            model_name='server',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='server',
            name='file_trans_status',
        ),
        migrations.RemoveField(
            model_name='server',
            name='init_param',
        ),
        migrations.RemoveField(
            model_name='server',
            name='is_rollback',
        ),
        migrations.RemoveField(
            model_name='server',
            name='salt_cmd',
        ),
    ]
